export enum SignStatuses {
  SUCCESS = 'SUCCESS',
  EMPTY = 'EMPTY FIELD',
  NOSPACES = 'INCLUDE SPACES',
  NOTENOUGH = 'NOT ENOUGH DATA',
  OVERFLOW = 'TOO MUCH SYMBOLS',
  WRONGSYM = 'WRONG SYMBOL',
  FAILED = 'OPERATION FAILED',
  NOTFOUND = 'EMAIL NOT FOUND',
  BADEMAIL = 'BAD EMAIL',
  BADPASSWORD = 'BAD PASSWORD',
  BADREPEAT = 'PASSWORDS NOT SAME',
  WRONGPASS = 'WRONG PASSWORD',
}
