export enum FetchStatus {
  SUCCESS = 'SUCCESS',
  PENDING = 'PENDING',
  FAILED = 'FAILED',
  WRONGURL = 'WRONG URL',
  NOTCONNECTED = 'NOT CONNECTED',
  CLIENTERROR = 'CLIENT ERROR',
  SERVERERROR = 'SERVERERROR',
}
